/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.diviso.graeshoppe.client.payment.api;

import com.diviso.graeshoppe.client.payment.model.PaymentDetails;
import com.diviso.graeshoppe.client.payment.model.PaymentHistory;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-08-15T15:41:55.844377+05:30[Asia/Kolkata]")

@Api(value = "PaypalQueryResource", description = "the PaypalQueryResource API")
public interface PaypalQueryResourceApi {

    @ApiOperation(value = "getAllPaymentsFromGateway", nickname = "getAllPaymentsFromGatewayUsingGET", notes = "", response = PaymentHistory.class, tags={ "paypal-query-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = PaymentHistory.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/paypal/payments",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<PaymentHistory> getAllPaymentsFromGatewayUsingGET();


    @ApiOperation(value = "getPayment", nickname = "getPaymentUsingGET1", notes = "", response = PaymentDetails.class, tags={ "paypal-query-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = PaymentDetails.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/payments/paypal/{payment_id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<PaymentDetails> getPaymentUsingGET1(@ApiParam(value = "payment_id",required=true) @PathVariable("payment_id") String paymentId);

}
