/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.diviso.graeshoppe.client.product.api;

import com.diviso.graeshoppe.client.product.model.Category;
import com.diviso.graeshoppe.client.product.model.CategoryDTO;
import java.util.List;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-11-29T15:19:12.817+05:30[Asia/Kolkata]")

@Api(value = "CategoryResource", description = "the CategoryResource API")
public interface CategoryResourceApi {

    @ApiOperation(value = "createCategory", nickname = "createCategoryUsingPOST", notes = "", response = CategoryDTO.class, tags={ "category-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CategoryDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/categories",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<CategoryDTO> createCategoryUsingPOST(@ApiParam(value = "categoryDTO" ,required=true )  @Valid @RequestBody CategoryDTO categoryDTO);


    @ApiOperation(value = "deleteCategory", nickname = "deleteCategoryUsingDELETE", notes = "", tags={ "category-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/categories/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteCategoryUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "exportCategoryListAsPdf", nickname = "exportCategoryListAsPdfUsingGET", notes = "", response = byte[].class, tags={ "category-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = byte[].class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/pdf/category-report/{idpcode}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<byte[]> exportCategoryListAsPdfUsingGET(@ApiParam(value = "idpcode",required=true) @PathVariable("idpcode") String idpcode);


    @ApiOperation(value = "getAllCategories", nickname = "getAllCategoriesUsingGET", notes = "", response = CategoryDTO.class, responseContainer = "List", tags={ "category-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CategoryDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/categories",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<CategoryDTO>> getAllCategoriesUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getCategory", nickname = "getCategoryUsingGET", notes = "", response = CategoryDTO.class, tags={ "category-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CategoryDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/categories/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<CategoryDTO> getCategoryUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "ListToDTo", nickname = "listToDToUsingPOST", notes = "", response = CategoryDTO.class, responseContainer = "List", tags={ "category-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CategoryDTO.class, responseContainer = "List"),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/category/listToDTO",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<List<CategoryDTO>> listToDToUsingPOST(@ApiParam(value = "categoryList" ,required=true )  @Valid @RequestBody List<Category> category);


    @ApiOperation(value = "searchCategories", nickname = "searchCategoriesUsingGET", notes = "", response = CategoryDTO.class, responseContainer = "List", tags={ "category-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CategoryDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/categories",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<CategoryDTO>> searchCategoriesUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateCategory", nickname = "updateCategoryUsingPUT", notes = "", response = CategoryDTO.class, tags={ "category-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CategoryDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/categories",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<CategoryDTO> updateCategoryUsingPUT(@ApiParam(value = "categoryDTO" ,required=true )  @Valid @RequestBody CategoryDTO categoryDTO);

}
