/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.diviso.graeshoppe.client.product.api;

import com.diviso.graeshoppe.client.product.model.TaxDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-11-29T15:19:12.817+05:30[Asia/Kolkata]")

@Api(value = "TaxResource", description = "the TaxResource API")
public interface TaxResourceApi {

    @ApiOperation(value = "createTax", nickname = "createTaxUsingPOST", notes = "", response = TaxDTO.class, tags={ "tax-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = TaxDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/taxes",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<TaxDTO> createTaxUsingPOST(@ApiParam(value = "taxDTO" ,required=true )  @Valid @RequestBody TaxDTO taxDTO);


    @ApiOperation(value = "deleteTax", nickname = "deleteTaxUsingDELETE", notes = "", tags={ "tax-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/taxes/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTaxUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllTaxes", nickname = "getAllTaxesUsingGET", notes = "", response = TaxDTO.class, responseContainer = "List", tags={ "tax-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = TaxDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/taxes",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<TaxDTO>> getAllTaxesUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getTax", nickname = "getTaxUsingGET", notes = "", response = TaxDTO.class, tags={ "tax-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = TaxDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/taxes/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<TaxDTO> getTaxUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchTaxes", nickname = "searchTaxesUsingGET", notes = "", response = TaxDTO.class, responseContainer = "List", tags={ "tax-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = TaxDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/taxes",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<TaxDTO>> searchTaxesUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateTax", nickname = "updateTaxUsingPUT", notes = "", response = TaxDTO.class, tags={ "tax-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = TaxDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/taxes",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<TaxDTO> updateTaxUsingPUT(@ApiParam(value = "taxDTO" ,required=true )  @Valid @RequestBody TaxDTO taxDTO);

}
