/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.diviso.graeshoppe.client.store.api;

import com.diviso.graeshoppe.client.store.model.UniqueStoreIDDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-12-02T13:57:13.442+05:30[Asia/Kolkata]")

@Api(value = "UniqueStoreIdResource", description = "the UniqueStoreIdResource API")
public interface UniqueStoreIdResourceApi {

    @ApiOperation(value = "createUniqueStoreID", nickname = "createUniqueStoreIDUsingPOST", notes = "", response = UniqueStoreIDDTO.class, tags={ "unique-store-id-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = UniqueStoreIDDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/unique-store-ids",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<UniqueStoreIDDTO> createUniqueStoreIDUsingPOST(@ApiParam(value = "uniqueStoreIDDTO" ,required=true )  @Valid @RequestBody UniqueStoreIDDTO uniqueStoreIDDTO);


    @ApiOperation(value = "deleteUniqueStoreID", nickname = "deleteUniqueStoreIDUsingDELETE", notes = "", tags={ "unique-store-id-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/unique-store-ids/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteUniqueStoreIDUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllUniqueStoreIDS", nickname = "getAllUniqueStoreIDSUsingGET", notes = "", response = UniqueStoreIDDTO.class, responseContainer = "List", tags={ "unique-store-id-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = UniqueStoreIDDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/unique-store-ids",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<UniqueStoreIDDTO>> getAllUniqueStoreIDSUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getUniqueStoreID", nickname = "getUniqueStoreIDUsingGET", notes = "", response = UniqueStoreIDDTO.class, tags={ "unique-store-id-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = UniqueStoreIDDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/unique-store-ids/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<UniqueStoreIDDTO> getUniqueStoreIDUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchUniqueStoreIDS", nickname = "searchUniqueStoreIDSUsingGET", notes = "", response = UniqueStoreIDDTO.class, responseContainer = "List", tags={ "unique-store-id-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = UniqueStoreIDDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/unique-store-ids",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<UniqueStoreIDDTO>> searchUniqueStoreIDSUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateUniqueStoreID", nickname = "updateUniqueStoreIDUsingPUT", notes = "", response = UniqueStoreIDDTO.class, tags={ "unique-store-id-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = UniqueStoreIDDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/unique-store-ids",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<UniqueStoreIDDTO> updateUniqueStoreIDUsingPUT(@ApiParam(value = "uniqueStoreIDDTO" ,required=true )  @Valid @RequestBody UniqueStoreIDDTO uniqueStoreIDDTO);

}
