/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.diviso.graeshoppe.client.order.api;

import com.diviso.graeshoppe.client.order.model.StatusDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-10-29T12:42:01.121660+05:30[Asia/Kolkata]")

@Api(value = "StatusResource", description = "the StatusResource API")
public interface StatusResourceApi {

    @ApiOperation(value = "createStatus", nickname = "createStatusUsingPOST", notes = "", response = StatusDTO.class, tags={ "status-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StatusDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/statuses",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<StatusDTO> createStatusUsingPOST(@ApiParam(value = "statusDTO" ,required=true )  @Valid @RequestBody StatusDTO statusDTO);


    @ApiOperation(value = "deleteStatus", nickname = "deleteStatusUsingDELETE", notes = "", tags={ "status-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/statuses/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteStatusUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllStatuses", nickname = "getAllStatusesUsingGET", notes = "", response = StatusDTO.class, responseContainer = "List", tags={ "status-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StatusDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/statuses",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<StatusDTO>> getAllStatusesUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getStatus", nickname = "getStatusUsingGET", notes = "", response = StatusDTO.class, tags={ "status-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StatusDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/statuses/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<StatusDTO> getStatusUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchStatuses", nickname = "searchStatusesUsingGET", notes = "", response = StatusDTO.class, responseContainer = "List", tags={ "status-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StatusDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/statuses",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<StatusDTO>> searchStatusesUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateStatus", nickname = "updateStatusUsingPUT", notes = "", response = StatusDTO.class, tags={ "status-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StatusDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/statuses",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<StatusDTO> updateStatusUsingPUT(@ApiParam(value = "statusDTO" ,required=true )  @Valid @RequestBody StatusDTO statusDTO);

}
